version: '3.3'

services:
  postgres:
    build:
      context: docker/db
      dockerfile: Dockerfile
    command: postgres
    environment:
      POSTGRES_DB: "kotlin-app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tolstochok3000"
    ports:
      - "5432:5432"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/tmp:/tmp:delegated"
    networks:
      app-network:
        ipv4_address: 172.25.1.2
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./testapp.jar
    ports:
      - "8080:8080"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/tmp:/tmp:delegated"
    networks:
      app-network:
        ipv4_address: 172.25.1.3
    depends_on:
      - postgres
    restart: always
networks:
  app-network:
    ipam:
      config:
        - subnet: 172.25.1.0/16