version: '3.3'

services:
  postgres:
    build:
      context: docker/db
      dockerfile: Dockerfile
    command: postgres
    environment:
      POSTGRES_DB: "kotlin-app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Tolstochok3000"
    ports:
      - "5432:5432"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/tmp:/tmp:delegated"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar ./testapp.jar
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/tmp:/tmp:delegated"
    depends_on:
      - postgres